// -------------------------------------------------------
//
// Brush Scripting
// Map: DEATHMATCH mp_rocket
// Last updated by: Agent
//
// -------------------------------------------------------

game_manager
{
	spawn
	{
		// Set scenario information

		wm_mapdescription		"Allied forces need to prevent the launch of the Axis V2 rocket."

		// Set the respawn times

		wm_allied_respawntime		30
		wm_axis_respawntime		30

		// ** DO NOT CHANGE THIS VALUE, SERVER ADMINS **
		// If you do, it may break some of the sound effects
		//
		wm_set_round_timelimit		15

		// Set the number of objectives for the map

		wm_number_of_objectives		5

		// Axis control all objectives at the start (0 == AXIS, 1 == ALLIED)
		wm_set_objective_status		1	0
		wm_set_objective_status		2	0
		wm_set_objective_status		3	0
		wm_set_objective_status		4	-1
		wm_set_objective_status		5	-1
		
		wm_objective_allied_desc	1	"Primary Objective:**Steal the Rocket Launch Override Key."
		wm_objective_allied_desc	2	"Primary Objective:**Get to the Override Console and use the Key."
		wm_objective_allied_desc	3	"Secondary Objective:**Destroy Emergency Rocket Bay Doors."
		wm_objective_allied_desc	4	"Secondary Objective:**Capture the First Cave."
		wm_objective_allied_desc	5	"Secondary Objective:**Clear Train tunnel cave-in."
		
		wm_objective_axis_desc		1	"Primary Objective:**Prevent Allies from stealing the Override key."
		wm_objective_axis_desc		2	"Primary Objective:**Stop the Allies from getting to the Override console."
		wm_objective_axis_desc		3	"Secondary Objective:**Defend Emergency Rocket Bay Doors."
		wm_objective_axis_desc		4	"Secondary Objective:**Hold the First Cave."
		wm_objective_axis_desc		5	"Secondary Objective:**Defend tunnel cave-in."
		
		wm_overview_image			"video/mp_rocket.roq"
		wm_objective_image			1	"gfx/2d/mp_objectives/rocket_obj_1.tga"
		wm_objective_image			2	"gfx/2d/mp_objectives/rocket_obj_2.tga"
		wm_objective_image			3	"gfx/2d/mp_objectives/rocket_obj_3.tga"
		wm_objective_image			4	"gfx/2d/mp_objectives/rocket_obj_4.tga"
		wm_objective_image			5	"gfx/2d/mp_objectives/rocket_obj_5.tga"

		// SHORT DESCRIPTIONS

		wm_objective_short_allied_desc	1	"Steal the Override key"
		wm_objective_short_allied_desc	2	"Use Override Console"
		wm_objective_short_allied_desc	3	"Destroy Emergency doors"
		wm_objective_short_allied_desc	4	"Capture first cave"
		wm_objective_short_allied_desc	5	"Clear Train tunnel"

		wm_objective_short_axis_desc	1	"Defend Override key"
		wm_objective_short_axis_desc	2	"Defend Override console"
		wm_objective_short_axis_desc	3	"Defend Emergency doors"
		wm_objective_short_axis_desc	4	"Hold first cave"
		wm_objective_short_axis_desc	5	"Defend Train tunnel"

		// Set Defending Team for SW Mode

		wm_set_defending_team	0

		// If the round timer expires, the Axis have won, so set the current winning team
		// Set the round winner:  0 == AXIS, 1 == ALLIED
		wm_setwinner 0

		// Accum #1 will be the state of objective number one
		accum 1 set 0
	}

	trigger axis_object_stolen
	{
		// Change the objective state internally, so UI can update, etc.
		// Allied have stolen the override key (0 == AXIS, 1 == ALLIED)
		wm_set_objective_status		1	1
	}

	trigger axis_object_returned
	{
		// Change the objective state internally, so UI can update, etc.
		// Axis have returned the override key (0 == AXIS, 1 == ALLIED)
		wm_set_objective_status		1	0
	}

	trigger upper_rocket_bay_door
	{
		// Change the objective state internally, so UI can update, etc.
		// Allied takes control of objective #1
		wm_set_objective_status		2	1

		// UI pop-up to alert players
		wm_announce	"Allies have destroyed the Upper Rocket Bay door!"
	}

	trigger lower_rocket_bay_door
	{
		// Change the objective state internally, so UI can update, etc.
		// Allied takes control of objective #1
		wm_set_objective_status		2	1

		// UI pop-up to alert players
		wm_announce	"Allies have destroyed the Rocket Bay Emergency Exit!"
	}

	trigger tunnel_rubble
	{
		// Change the objective state internally, so UI can update, etc.
		// Axis takes control of checkpoint #1
		wm_set_objective_status		5	1

		// Some kind of UI pop-up to alert players
		wm_announce	"Allies have broken through train tunnel cave in!"
	}

	trigger override_console
	{
		// Change the objective state internally, so UI can update, etc.
		// Allied takes control of objective #1
		wm_set_objective_status		3	1

		// Change the variable within the script so that we can check if someone wins the round
		accum 1 set 1

		// UI pop-up to alert players
		wm_announce	"Override console been used, rocket launch aborted!"

		// Call function to check if the round has been won
		trigger game_manager checkgame
	}

	trigger cave_flagblue
	{
		// Change the objective state internally, so UI can update, etc.
		// Allied takes control of checkpoint #1
		wm_set_objective_status		4	1

		// Some kind of UI pop-up to alert players
		wm_announce	"Allies capture the First Cave!"
	}

	trigger cave_flagred
	{
		// Change the objective state internally, so UI can update, etc.
		// Axis takes control of checkpoint #1
		wm_set_objective_status		4	-1

		// Some kind of UI pop-up to alert players
		wm_announce	"Axis reclaims the First Cave!"
	}

	trigger timelimit_hit
	{
		// Launch Rocket
		stopsound
		trigger v2_rocket launch
	}

	trigger checkgame
	{
		accum 1 abort_if_not_equal 1

		// Set the round winner:  0 == AXIS, 1 == ALLIED
		wm_setwinner 1

		// Blow up rocket
		stopsound
		trigger counter3 destroy_v2

		// End the round
		wm_endround
	}
}

destroy_upper_rocket_bay_door //Upper Rocket bay door.
{
	spawn
	{
		remove
	}
}

destroy_lower_rocket_bay_door //Lower Rocket bay door. Emergency Exit
{
	spawn
	{
		remove
	}

}

install_override_key //Got to console and installed key
{
	spawn
	{
		remove
	}
}

caveone_flag
{
	spawn
	{
		remove
	}
}

flag_respawn_base
{
	spawn
	{
		remove
	}
}

destroy_tunnel_rubble
{
	spawn
	{
		remove
	}
}

// -------------------------------------------------------
// Big Rocket Bay double doors - MP_base code v2 ;)
// 10s delay is set in the entities so people don't hog
// the switch routine
// -------------------------------------------------------

rocdoor_trigger1
{
	spawn
	{
		remove
	}

}

// Code for levers, sound effects and path_corners
rocdoor_lever1
{
	spawn
	{
		remove
	}
}

rocdoor_invtrig1
{
	spawn
	{
		remove
	}
}

rocdoor_invtrig2
{
	spawn
	{
		remove
	}
}

plate_lever1
{
	spawn
	{
		remove
	}
}

plate_lever2
{
	spawn
	{
		remove
	}
}

rocdoor_lever2
{
	spawn
	{
		remove
	}
}

// Code for doors, sound effects and path_corners
rocdoor_left
{
	spawn
	{
		wait 500
		playsound sound/scenaric/assault/big_gate1.wav
		wait 400
		playsound sound/scenaric/assault/big_gate2.wav looping forever
		gotomarker rocdoor_leftpos2 15 wait
		stopsound
		playsound sound/scenaric/assault/big_gate3.wav
	}
}

rocdoor_right
{
	spawn
	{
		wait 500
		playsound sound/scenaric/assault/big_gate1.wav
		wait 400
		playsound sound/scenaric/assault/big_gate2.wav looping forever
		gotomarker rocdoor_rightpos2 18 wait
		stopsound
		playsound sound/scenaric/assault/big_gate3.wav
	}
}

// -------------------------------------------------------
// Counter 1 - Used for the FINAL rocket countdown
// -------------------------------------------------------
counter1
{
	spawn
	{
// Removed because people may change the timelimit of the map and cause the time samples
// to go out of sync. Oh well such as life. :\
//
//		wait 600000			// 10 minutes (T-Minus 2)
		// print Final count to launch
//		alertentity ls_2min		// print ATTENTION ALL PERSONELL...V2 will launch in 2 minutes.
//		wait 25000
//		alertentity ls_1min30sec	// print Launch will commence in 1 minute 30 seconds.
//		wait 30000
//		alertentity ls_1min		// print Launch will commence in 1 minute.

//		alertentity v2_lights		// Dlight entities
//		wait 30000

//		alertentity ls_30sec		// print Launch will commence in 30 seconds.
//		wait 15000
//		alertentity ls_15sec		// print Launch will commence in 15 seconds.
//		wait 5000
//		alertentity ls_1098765sec	// print Launch will commence in 10 seconds.
	}
}

// -------------------------------------------------------
// Counter 2 - Used for the TEST rocket test and
//             misc. messages throughout game
// -------------------------------------------------------
counter2
{
	spawn
	{
		wait 60000			// 1 minute - wait for map warmup to be over
		// print Start rocket test
		alertentity ls_attention	// print ATTENTION ALL PERSONELL...
		wait 6600
		alertentity ls_54321		// print V2 ROCKET TEST GOING TO COMMENCE IN...5..4..3..2..1
		wait 7250
		alertentity v2_lowersmoke	// Start base smoke
		alertentity rumble1		// Big rumble sound
		wait 12000
		alertentity ls_test_complete	// print V2 ROCKET TEST COMPLETE.
		alertentity v2_lowersmoke	// Shut off base smoke

		wait 120000			// 2 minutes (T-Minus 8)
		alertentity ls_fueling		// Misc chatter

		wait 120000			// 2 minutes (T-Minus 6)
		alertentity ls_tower		// Misc chatter
	}
}

// -------------------------------------------------------
// Counter 3 - Used for destroying the rocket, cannot kill
//             the original entity.
// -------------------------------------------------------
counter3
{
	spawn
	{
	}
	
	trigger destroy_v2
	{
		wait 2500	// let camera get setup correctly
		alertentity v2_blow1
		wait 1000
		alertentity v2_smoke1 // Turns off v2_smoke

		wait 100
		alertentity kill_v2_rocket // Kills rocket
		alertentity rumble2 // Triggers the rumble.
		alertentity v2_explosion // Triggers the v2_explosions/func_explosives.
		trigger beam4 go
		trigger beam5 go
		trigger beam6 go
		trigger block1 go
		trigger block2 go
		trigger block3 go
		trigger block4 go
		trigger block5 go
		trigger block6 go
		trigger v2_support go
		trigger v2_funnel go
		trigger v2_gangway go
		wait 5
		alertentity v2_explosion2 // Triggers some func_explosives.
		wait 5
		alertentity v2_explosion3 // Triggers some func_explosives.
		wait 15000	// Pause for thought
	}
}

// -------------------------------------------------------
// Dummy entities used in the player's rocket bay room
// -------------------------------------------------------
v2mod_rocket	// B-i-g rocket baby
{
	spawn
	{
		wait 100			// Wait for all entities to spawn in map
		faceangles 0 90 0 100
		gotomarker v2modspot0 10000	// Move rocket to position
		alertentity v2_start_topsmoke	// Start up V2 rocket top smoke
	}

}
v2mod_gangway	// Support structure around rocket
{
	spawn
	{
		wait 100			// Wait for all entities to spawn in map
		faceangles 0 90 0 100
	}
}
v2mod_support	// Rocket sits on this
{
	spawn
	{
		wait 100			// Wait for all entities to spawn in map
		faceangles 0 90 0 100
	}
}
v2mod_funnel	// Rocket burner base
{
	spawn
	{
		wait 100			// Wait for all entities to spawn in map
		faceangles 0 90 0 100
	}
}

// -------------------------------------------------------
// Spawn train wait 15 seconds and then start it.
// -------------------------------------------------------
train1
{
	spawn
	{
		wait 15000			// Wait 15secs to start journey
		trigger train1 straight1	// Start train on journey
	}


	// Move away upper door
	trigger straight1
	{
		trigger traingear rotate1
		wait 2000
		playsound sound/scenaric/rocket/elec_train_start.wav
		gotomarker trainspot01 50
		faceangles 0 0 0 gototime
		playsound sound/scenaric/rocket/elec_train_loop.wav looping
		gotomarker trainspot02 50
		faceangles 0 0 0 gototime
		trigger train1 turn1
	}

	// First corner in first room
	trigger turn1
	{
		trigger trainrw right_15
		gotomarker trainspot03 50
		faceangles 0 -5 0 gototime
		trigger trainfw right_15
		gotomarker trainspot04 60
		faceangles 0 -10 0 gototime
		gotomarker trainspot05 70
		trigger traingear rotate2
		faceangles 0 -22 0 gototime
		gotomarker trainspot06 80
		faceangles 0 -36 0 gototime
		gotomarker trainspot07 90
		trigger traingear rotate3
		faceangles 0 -52 0 gototime
		gotomarker trainspot08 100
		faceangles 0 -64 0 gototime
		gotomarker trainspot09 110
		faceangles 0 -74 0 gototime
		trigger traingear rotate4
		trigger trainrw center
		gotomarker trainspot10 120
		faceangles 0 -85 0 gototime
		trigger trainfw center
		gotomarker trainspot11 130
		trigger traingear rotate5
		faceangles 0 -90 0 gototime
		
		trigger train1 straight2
	}

	// Moving out of first room
	trigger straight2
	{
		gotomarker trainspot12 150
		faceangles 0 -90 0 gototime
		gotomarker trainspot13 150
		faceangles 0 -90 0 gototime
		gotomarker trainspot16 150
		trigger traingear rotate6
		faceangles 0 -90 0 gototime
		
		trigger train1 turn2
	}

	// First part of S bend
	trigger turn2
	{
		trigger trainrw right_15
		gotomarker trainspot17 120
		faceangles 0 -95 0 gototime
		trigger trainfw right_15
		gotomarker trainspot18 110
		faceangles 0 -100 0 gototime
		gotomarker trainspot19 100
		faceangles 0 -112 0 gototime
		gotomarker trainspot20 90
		faceangles 0 -126 0 gototime
		gotomarker trainspot21 80
		faceangles 0 -142 0 gototime
		gotomarker trainspot22 90
		faceangles 0 -154 0 gototime
		gotomarker trainspot23 100
		faceangles 0 -164 0 gototime
		trigger trainrw center
		gotomarker trainspot24 110
		faceangles 0 -175 0 gototime
		trigger trainfw center
		gotomarker trainspot25 100
		faceangles 0 -180 0 gototime
		
		trigger train1 turn3
	}
	
	// Second part of S bend
	trigger turn3
	{
		trigger trainrw left_15
		gotomarker trainspot26 90
		faceangles 0 -175 0 gototime
		trigger trainfw left_15
		gotomarker trainspot27 80
		faceangles 0 -164 0 gototime
		gotomarker trainspot28 70
		faceangles 0 -154 0 gototime
		gotomarker trainspot29 80
		faceangles 0 -142 0 gototime
		gotomarker trainspot30 90
		faceangles 0 -126 0 gototime
		gotomarker trainspot31 100
		faceangles 0 -112 0 gototime
		trigger trainrw center
		gotomarker trainspot32 120
		faceangles 0 -100 0 gototime
		trigger trainfw center
		gotomarker trainspot33 150
		faceangles 0 -95 0 gototime
		trigger train1 straight3
	}

	// Over canyon bridge
	trigger straight3
	{
		gotomarker trainspot34 250
		faceangles 0 -90 0 gototime
		gotomarker trainspot35 300
		faceangles 0 -90 0 gototime
		gotomarker trainspot36 300
		faceangles 0 -90 0 gototime
		gotomarker trainspot37 300
		faceangles 0 -90 0 gototime
		gotomarker trainspot38 300
		faceangles 0 -90 0 gototime
		gotomarker trainspot39 300
		faceangles 0 -90 0 gototime
		gotomarker trainspot40 225
		faceangles 0 -90 0 gototime
		gotomarker trainspot41 175
		faceangles 0 -90 0 gototime
		
		trigger train1 turn4
	}

	// Corner approaching cave-in section
	trigger turn4
	{
		trigger trainrw right_15
		gotomarker trainspot42 120
		faceangles 0 -95 0 gototime
		trigger trainfw right_15
		gotomarker trainspot43 110
		faceangles 0 -100 0 gototime
		gotomarker trainspot44 100
		faceangles 0 -112 0 gototime
		gotomarker trainspot45 100
		faceangles 0 -126 0 gototime
		gotomarker trainspot46 110
		faceangles 0 -142 0 gototime
		gotomarker trainspot47 120
		faceangles 0 -154 0 gototime
		gotomarker trainspot48 130
		faceangles 0 -164 0 gototime
		trigger trainrw center
		gotomarker trainspot49 140
		faceangles 0 -175 0 gototime
		trigger trainfw center
		gotomarker trainspot50 150
		faceangles 0 -180 0 gototime
		
		trigger train1 straight4
	}

	// Moving past cave-in section
	trigger straight4
	{
		gotomarker trainspot51 200
		faceangles 0 -180 0 gototime
		gotomarker trainspot52 350
		faceangles 0 -180 0 gototime
		gotomarker trainspot53 250
		faceangles 0 -180 0 gototime
		
		trigger train1 turn5
	}

	// Corner leading towards second bridge with ladder up
	trigger turn5
	{
		trigger trainrw right_15
		gotomarker trainspot54 150
		faceangles 0 -185 0 gototime
		trigger trainfw right_15
		gotomarker trainspot55 140
		faceangles 0 -190 0 gototime
		gotomarker trainspot56 130
		faceangles 0 -202 0 gototime
		gotomarker trainspot57 120
		faceangles 0 -216 0 gototime
		gotomarker trainspot58 130
		faceangles 0 -232 0 gototime
		gotomarker trainspot59 140
		faceangles 0 -244 0 gototime
		gotomarker trainspot60 140
		faceangles 0 -254 0 gototime
		trigger trainrw center
		gotomarker trainspot61 150
		faceangles 0 -265 0 gototime
		trigger trainfw center
		gotomarker trainspot62 175
		faceangles 0 -270 0 gototime
		
		trigger train1 straight5
	}

	// Over the second bridge past the ladder
	trigger straight5
	{
		gotomarker trainspot63 225
		faceangles 0 -270 0 gototime
		gotomarker trainspot64 300
		faceangles 0 -270 0 gototime
		gotomarker trainspot65 300
		faceangles 0 -270 0 gototime
		gotomarker trainspot66 225
		faceangles 0 -270 0 gototime
		gotomarker trainspot67 175
		faceangles 0 -270 0 gototime
		
		trigger train1 turn6
	}

	// Corner approaching starting point of loop
	trigger turn6
	{
		trigger trainrw right_15
		gotomarker trainspot68 150
		faceangles 0 -275 0 gototime
		trigger trainfw right_15
		gotomarker trainspot70 140
		faceangles 0 -280 0 gototime
		gotomarker trainspot71 130
		faceangles 0 -292 0 gototime
		gotomarker trainspot72 120
		faceangles 0 -306 0 gototime
		gotomarker trainspot73 130
		faceangles 0 -322 0 gototime
		gotomarker trainspot74 140
		faceangles 0 -334 0 gototime
		gotomarker trainspot75 140
		faceangles 0 -344 0 gototime
		trigger trainrw center
		gotomarker trainspot76 150
		faceangles 0 -355 0 gototime
		trigger trainfw center
		gotomarker trainspot77 175
		faceangles 0 0 0 gototime
		
		trigger train1 straight6
	}

	// straight section past the small entrance to the main cave
	trigger straight6
	{
		gotomarker trainspot78 250
		faceangles 0 0 0 gototime
		gotomarker trainspot79 300
		faceangles 0 0 0 gototime
		gotomarker trainspot80 250
		faceangles 0 0 0 gototime
		gotomarker trainspot81 175
		faceangles 0 0 0 gototime
		
		trigger train1 turn7
	}

	// Final corner to close the loop
	trigger turn7
	{
		trigger trainrw right_15
		gotomarker trainspot81 150
		faceangles 0 -5 0 gototime
		trigger trainfw right_15
		gotomarker trainspot82 140
		faceangles 0 -10 0 gototime
		gotomarker trainspot83 130
		faceangles 0 -22 0 gototime
		gotomarker trainspot84 120
		faceangles 0 -36 0 gototime
		gotomarker trainspot85 130
		faceangles 0 -52 0 gototime
		gotomarker trainspot86 140
		faceangles 0 -64 0 gototime
		gotomarker trainspot87 140
		faceangles 0 -74 0 gototime
		trigger trainrw center
		gotomarker trainspot88 150
		faceangles 0 -85 0 gototime
		trigger trainfw center
		gotomarker trainspot33 175
		faceangles 0 -90 0 gototime
		
		trigger train1 straight3
	}
}

// -------------------------------------------------------
// Big turning wheel at front of train.
// Attach to train model and wait for trigger from train script.
// -------------------------------------------------------
traingear
{
	spawn
	{
		wait 100
		attachtotag train1 tag_gen01
		wait 5
		faceangles 0 90 0 1000
	}

	trigger rotate1
	{
		faceangles 0 90 90 1200
		faceangles 0 90 180 1200
		faceangles 0 90 270 1200
		faceangles 0 90 360 1200
		trigger traingear rotate1
	}

	trigger rotate2
	{
		faceangles 0 90 90 1000
		faceangles 0 90 180 1000
		faceangles 0 90 270 1000
		faceangles 0 90 360 1000
		trigger traingear rotate2
	}

	trigger rotate3
	{
		faceangles 0 90 90 800
		faceangles 0 90 180 800
		faceangles 0 90 270 800
		faceangles 0 90 360 800
		trigger traingear rotate3
	}

	trigger rotate4
	{
		faceangles 0 90 90 600
		faceangles 0 90 180 600
		faceangles 0 90 270 600
		faceangles 0 90 360 600
		trigger traingear rotate4
	}

	trigger rotate5
	{
		faceangles 0 90 90 400
		faceangles 0 90 180 400
		faceangles 0 90 270 400
		faceangles 0 90 360 400
		trigger traingear rotate5
	}

	trigger rotate6
	{
		faceangles 0 90 90 200
		faceangles 0 90 180 200
		faceangles 0 90 270 200
		faceangles 0 90 360 200
		trigger traingear rotate6
	}

	trigger stop
	{
		faceangles 0 90 90 200
		faceangles 0 90 180 225
		faceangles 0 90 270 250
		faceangles 0 90 360 275
		faceangles 0 90 90 300
		faceangles 0 90 180 325
		faceangles 0 90 270 350
		faceangles 0 90 360 375
		faceangles 0 90 90 400
		faceangles 0 90 180 425
		faceangles 0 90 270 450
		faceangles 0 90 360 475
		faceangles 0 90 90 500
		faceangles 0 90 180 525
		faceangles 0 90 270 550
		faceangles 0 90 360 575
		faceangles 0 90 90 600
		faceangles 0 90 180 625
		faceangles 0 90 270 650
		faceangles 0 90 360 675
		resetscript
	}
}

// -------------------------------------------------------
// Front set of wheels on train.
// Attach to train model and wait for trigger from train script.
// -------------------------------------------------------
trainfw
{
	spawn
	{
		wait 100
		attachtotag train1 tag_wF
		wait 5
		faceangles 0 90 0 1000
	}

	trigger right_15
	{
		faceangles 0 105 0 2000
	}

	trigger left_20
	{
		faceangles 0 75 0 2000
	}

	trigger center
	{
		faceangles 0 90 0 1000
	}
}

// -------------------------------------------------------
// Back set of wheels on train.
// Attach to train model and wait for trigger from train script.
// -------------------------------------------------------
trainrw
{
	spawn
	{
		wait 100
		attachtotag train1 tag_wR
		wait 5
		faceangles 0 90 0 1000
	}

	trigger right_20
	{
		faceangles 0 75 0 2000
	}

	trigger left_15
	{
		faceangles 0 105 0 2000
	}

	trigger center
	{
		faceangles 0 90 0 1000
	}
}

//**********************************************************************************************
//
// ALL entities required for gameover sequences
//
//**********************************************************************************************
v2_rocket
{
	spawn
	{
		wait 500
		faceangles 0 90 0 100
		alertentity v2_smoke1	// START side smoke
	}

	trigger launch
	{
		alertentity rumble3
		wait 600
		alertentity v2_flame1	// START 1 smoke (3 at bottom)
		alertentity v2_flame2	// START 2 smoke
		alertentity start_flame	// Ignite Flame
		
		gotomarker v2spot1 100 accel wait

		alertentity v2_flame1	// STOP 1 smoke (3 at bottom)
		alertentity v2_smoke1	// STOP side smoke
		alertentity v2_flame3	// START 3 smoke
		gotomarker v2spot2 100 wait

		alertentity v2_flame2	// STOP 2 smoke
		alertentity v2_flame4	// START 4 smoke 
		gotomarker v2spot3 100 wait

		alertentity v2_flame3	// STOP 3 smoke
		alertentity v2_flame5	// START 5 smoke
		gotomarker v2spot4 150 wait

		alertentity v2_flame4	// STOP 4 smoke
		gotomarker v2spot5 150 wait
		
		wait 1000
		alertentity v2_flame5	// STOP 5 smoke
		wait 4000
		alertentity start_flame	// STOP Flame
		wait 10000	// Pause for thought
	}
}

v2_gangway
{
	spawn
	{
		wait 500
		faceangles 0 90 0 100
	}
	trigger go
	{
		gotomarker v2_gangwayspot1 100
		faceangles 51 92 17 gototime
		alertentity v2_explosion4
	}
}

v2_support
{
	spawn
	{
		wait 500
		faceangles 0 90 0 100
	}
	trigger go
	{
		gotomarker v2_suppspot1 100
		faceangles 15 0 10 gototime
	}
}

v2_funnel
{
	spawn
	{
		wait 500
		faceangles 0 90 0 100
	}
	trigger go
	{
		gotomarker v2_funnelspot1 100
		faceangles -15 0 -10 gototime
	}
}

beam1
{
	spawn
	{
		wait 5
		trigger beam1 go
	}
	trigger go
	{
		faceangles -8 0 0 1000
	}
}

beam2
{
	spawn
	{
		wait 5
		gotomarker beam2spot1 1000 wait
	}
	trigger swingloop
	{
		faceangles -76 0 0 3000
		faceangles -73 0 0 3000
		trigger beam2 swingloop
	}
}

beam3
{
	spawn
	{
		wait 5
		trigger beam3 go
	}
	trigger go
	{
		faceangles 15 0 0 1000
	}
}

beam4
{
	spawn
	{
	}
	trigger go
	{
		wait 500
		faceangles 0 0 64 3000
		wait 2000 0
		gotomarker beam4spot1 500
		faceangles 0 0 70 gototime
		gotomarker beam4spot2 500
		faceangles 0 0 75 gototime
		gotomarker beam4spot3 400
		faceangles 0 0 75 gototime
		gotomarker beam4spot4 500
		faceangles 0 0 68 gototime
		gotomarker beam4spot5 500
		faceangles 0 0 59 gototime
		gotomarker beam4spot6 500
		faceangles 0 0 52 gototime
		gotomarker beam4spot7 500
		faceangles 0 0 43 gototime
	}
}

beam5
{
	spawn
	{
	}
	trigger go
	{
		wait 500
		faceangles 0 0 24 2000
	}
}

beam6
{
	spawn
	{
	}
	trigger go
	{
		wait 500
		faceangles 0 0 -24 2000
	}
}

block1
{
	spawn
	{
	}
	trigger go
	{
		gotomarker block1spot1 1000
		faceangles 0 -35 10 gototime
	}
}

block2
{
	spawn
	{
	}
	trigger go
	{
		gotomarker block2spot1 1000
		faceangles 60 60 50 gototime
	}
}

block3
{
	spawn
	{
	}
	trigger go
	{
		gotomarker block3spot1 1000
		faceangles -20 60 -10 gototime
	}
}

block4
{
	spawn
	{
	}
	trigger go
	{
		gotomarker block4spot1 1000
		faceangles 0 20 0 gototime
	}
}

block5
{
	spawn
	{
	}
	trigger go
	{
		gotomarker block5spot1 1000
		faceangles 0 -60 80 gototime
	}
}

block6
{
	spawn
	{
	}
	trigger go
	{
		gotomarker block6spot1 1000
		faceangles -30 -20 0 gototime
	}
}
